export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';

export const REQUEST_CATS_PENDING='REQUEST_CATS_PENDING';
export const REQUEST_CATS_SUCCESS='REQUEST_CATS_SUCCESS';
export const REQUEST_CATS_FAILED='REQUEST_CATS_FAILED';

export const REQUEST_QUOTES_PENDING='REQUEST_QUOTES_PENDING';
export const REQUEST_QUOTES_SUCCESS='REQUEST_QUOTES_SUCCESS';
export const REQUEST_QUOTES_FAILED='REQUEST_QUOTES_FAILED';
